### ISSUE TITLE
我想把文章归档的url路径由“post”改成“archives”，怎么不行呢？

### ISSUE THREAD

**Issue by iDvel** [xianmin/hugo-theme-jane#100]
```
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "post"
  url = "/post/"
```
改成
```
  url = "/archives/"
```
为什么显示404呢  (●ﾟωﾟ●) 请教下怎么正确修改呀？

**Comment by jostyee** [comment]
文件目录改了么

**Comment by jostyee** [comment]
```toml
[permalinks]
  post = "/archives/:filename"
```
