### ISSUE TITLE
Social media icons not displayed in the footer by default (caused by Fanboy’s Annoyance List/Fanboy’s Social Blocking List)

### ISSUE THREAD

**Issue by limpehsh** [xianmin/hugo-theme-jane#108]
How do you get the social media icons to load nicely? I checked `.social-links` in `src/_partial/_footer/_social.scss`  which is fine but I nothing gets rendered in
`<div class="social-links">...</div>`

**Comment by xianmin** [comment]
You need set config to display `social media icons` : 

https://github.com/xianmin/hugo-theme-jane/blob/1af02095e0f72916e1f4f54737215e36a6140c20/exampleSite/config.toml#L137

And the icons source code in `src/_partial/_footer/_iconfont.scss` .

**Comment by limpehsh** [comment]
Strange, I have `[params.social]` in the same format as `config.toml.` I have also copied `src/css/_iconfont.scss` to `src/_partial/_footer/` since it was not there but I still experience the same issue. Also, when removing the social-links class, though I am able render the icons, I can't view the Twitter, Facebook, LinkedIn, Google, Github, Pocket, Tumblr and Instagram icons

**Comment by xianmin** [comment]
@limpehsh I'm sorry for previous message.
The icons source code in `src/_partial/_iconfont.scss` , not `src/_partial/_footer/_iconfont.scss`.

**Comment by xianmin** [comment]
Do you follow the README.md step by step and it doesn't work?
https://github.com/xianmin/hugo-theme-jane#quick-start

**Comment by limpehsh** [comment]
I did follow the README.md. That's why I'm very confused. I tried following the README.md before typing this response again and I still get nothing with the social-links class. Doesn't help that I can't see the social media icons in the demo either

**Comment by xianmin** [comment]
I try a new `hugo-site` use current `hugo-theme-jane` theme. And use a very short config:

```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "jane"

[author]                  # essential                     # 必需
  name = "xianmin"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params.social]                                         # 社交链接
  a-email = "mailto:your@email.com"
  b-stack-overflow = "http://en.xianmin.org/hugo-theme-jane/"
  c-twitter = "http://en.xianmin.org/hugo-theme-jane/"
  d-facebook = "http://en.xianmin.org/hugo-theme-jane/"
  e-linkedin = "http://en.xianmin.org/hugo-theme-jane/"
  f-google = "http://en.xianmin.org/hugo-theme-jane/"
  g-github = "http://en.xianmin.org/hugo-theme-jane/"
  h-weibo = "http://en.xianmin.org/hugo-theme-jane/"
  i-zhihu = "http://en.xianmin.org/hugo-theme-jane/"
  j-douban = "http://en.xianmin.org/hugo-theme-jane/"
  k-pocket = "http://en.xianmin.org/hugo-theme-jane/"
  l-tumblr = "http://en.xianmin.org/hugo-theme-jane/"
  m-instagram = "http://en.xianmin.org/hugo-theme-jane/"
  n-gitlab = "http://en.xianmin.org/hugo-theme-jane/"
  o-goodreads = "http://en.xianmin.org/hugo-theme-jane/"
  p-coding = "http://en.xianmin.org/hugo-theme-jane/"
```

It works.
I'm very confused too...

Do you try keyboard shortcut `CTRL+SHIFT+R` to force reload browser?
