### ISSUE TITLE
css code font-family different between English and other languages 

### ISSUE THREAD

**Issue by MrBenWang** [xianmin/hugo-theme-jane#161]
the red text are very different!It's markdown code:   `` `monospace` ``. They are Japanese，Chinese，English。I found the reason.  font-family .
下图的红色字体，差别比较大，是markdown语法，单引号生成的。由于 font-family 文字库造成的，关于字体类型我也不是很了解。

![_20181226162253](https://user-images.githubusercontent.com/9692054/50438962-2cb7d680-092b-11e9-9723-556cb09974af.jpg)

```css
.post .post-content code,.post .post-content pre {
    font-size: .9em;
    font-family: Menlo,Consolas,source code pro,Inconsolata,Monaco,courier new,monospace
}
```
