### ISSUE TITLE
i18n not working?

### ISSUE THREAD

**Issue by razonyang** [xianmin/hugo-theme-jane#183]
I follow the README steps to create a new site, and changed default language to "zh-cn":

```toml
defaultContentLanguage = "zh-cn"           # Default language to use
[languages.en]
  languageCode = "en"
[languages.zh-cn]
  languageCode = "zh-cn"
```

Hugo version
> Hugo Static Site Generator v0.54.0/extended linux/amd64 BuildDate: unknown
