### ISSUE TITLE
How to adjust the order of 'docs' in the menu?

### ISSUE THREAD

**Issue by CicoZhang** [xianmin/hugo-theme-jane#198]
How to adjust the order of 'docs' (as an example here) in the menu?
![image](https://user-images.githubusercontent.com/11710225/59149628-fa50f000-8a17-11e9-8f0c-0928675da3ce.png)

```
menu:
  main:
    parent: "docs"
    weight: 1
```
The code above only lets the article appear as first under 'docs', how can I adjust the weight of 'docs' to let it not stay at the end of the menu? 

Thanks in advance.
