### ISSUE TITLE
首页文章不显示了

### ISSUE THREAD

**Issue by Liudon** [xianmin/hugo-theme-jane#244]
网站地址 [https://liudon.xyz/](https://liudon.xyz/)

![image](https://user-images.githubusercontent.com/5969707/64220374-c2185b00-cefb-11e9-9f44-a5de1fcdd780.png)

点到Posts里，可以显示文章。

![image](https://user-images.githubusercontent.com/5969707/64220439-0d326e00-cefc-11e9-92ce-0fb7abe2e89d.png)

config.toml配置如下：

```
# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://liudon.xyz"
title = "流动 - 生活就是一个流动的过程"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 5              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-18074379-5"      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use
[languages.zh-cn]
  languageCode = "zh-cn"

[author]                  # essential                     # 必需
  name = "liudon"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 30
  identifier = "about"
  url = "/about/"

[params]
  since = "2011"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "流动"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["生活", "代码"]
  description = "生活就是一个流动的过程."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.publicCDN]        # load these files from public cdn
    # 启用公共CDN，需自行定义
    enable = true
    jquery = '<script src="//cdn.staticfile.org/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>'
    slideout = '<script src="//cdn.staticfile.org/slideout/1.0.1/slideout.min.js" crossorigin="anonymous"></script>'
    photoswipe = '<script src="//cdn.staticfile.org/photoswipe/4.1.3/photoswipe.min.js"  crossorigin="anonymous"></script>'
    photoswipeUI = '<script src="//cdn.staticfile.org/photoswipe/4.1.3/photoswipe-ui-default.min.js" crossorigin="anonymous"></script>'
    photoswipeCSS = '<link rel="stylesheet" href="//cdn.staticfile.org/photoswipe/4.1.3/photoswipe.min.css" crossorigin="anonymous">'
    photoswipeSKIN = '<link rel="stylesheet" href="//cdn.staticfile.org/photoswipe/4.1.3/default-skin/default-skin.css" crossorigin="anonymous">'

  [params.social]                                         # 社交链接
    #a-email = "mailto:your@email.com"
    #b-stack-overflow = "http://localhost:1313"
    #c-twitter = "http://localhost:1313"
    #d-facebook = "http://localhost:1313"
    #e-linkedin = "http://localhost:1313"
    #f-google = "http://localhost:1313"
    #g-github = "http://localhost:1313"
    #h-weibo = "http://localhost:1313"
    #i-zhihu = "http://localhost:1313"
    #j-douban = "http://localhost:1313"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "http://localhost:1313"
    #n-gitlab = "http://localhost:1313"
    #o-goodreads = "http://localhost:1313"
    #p-coding = "http://localhost:1313"
    #q-bilibili = "http://localhost:1313"

```

**Comment by Liudon** [comment]
```
Building sites … WARN 2019/09/04 01:38:52 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/09/04 01:38:52 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/09/04 01:38:52 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
```

build的时候有这么一个warning

**Comment by RocFang** [comment]
是不是更新了hugo版本？hugo中间有过一次不兼容的变更，jane这个主题后来已经跟进了，你更新一下应该可以的。

**Comment by Liudon** [comment]
在本机部署没问题，但是在travis-ci上就是不行。

```
$ go version
go version go1.11.13 linux/amd64
go.env
$ go env
install
186.08s$ go get github.com/gohugoio/hugo
before_script
0.01s$ rm -rf public 2> /dev/null
0.25s$ hugo -v --gc
INFO 2019/09/04 11:30:49 Using config file: 
Building sites … INFO 2019/09/04 11:30:49 syncing static files to /home/travis/gopath/src/github.com/Liudon/[secure].github.io/public/
WARN 2019/09/04 11:30:49 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/09/04 11:30:49 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/09/04 11:30:49 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
                   | ZH-CN  
-------------------+--------
  Pages            |    27  
  Paginator pages  |     0  
  Non-page files   |     0  
  Static files     |    19  
  Processed images |     0  
  Aliases          |     6  
  Sitemaps         |     1  
  Cleaned          |     2  
Total in 153 ms
The command "hugo -v --gc" exited with 0.
```

**Comment by shaform** [comment]
要更新 hugo-theme-jane 的版本，從那些 warning 可知你還是用舊版本的 hugo-theme-jane.

**Comment by Liudon** [comment]
> 要更新 hugo-theme-jane 的版本，從那些 warning 可知你還是用舊版本的 hugo-theme-jane.

```
$ git clone --depth=50 --branch=code https://github.com/Liudon/[secure].github.io.git Liudon/[secure].github.io
git.submodule
$ git submodule update --init --recursive
Submodule 'themes/jane' (https://github.com/xianmin/hugo-theme-jane.git) registered for path 'themes/jane'
Cloning into '/home/travis/build/Liudon/[secure].github.io/themes/jane'...
Submodule path 'themes/jane': checked out '0d759e3fd71bf724c3b307c6d5a4be5fa8903cf8'
```

每次部署都是重新clone的，肯定是最新的了。

**Comment by shaform** [comment]
從你提供的訊息可知他 checkout 了這個版本，並不是最新的 
 0d759e3fd71bf724c3b307c6d5a4be5fa8903cf8

**Comment by RocFang** [comment]
从你提供的信息来看，你可能还不熟悉git submodule的相关操作，看一下就好了。@Liudon

**Comment by Liudon** [comment]
解决了，感谢 @shaform @RocFang .

确实是git submodule的问题。

修改.travis.yml

```
# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/

language: go

python:
    - master

# before_install
# install - install any dependencies required
install:
    - go get github.com/gohugoio/hugo

git:
  submodules: false # 不运行 git submodules 命令

before_script:
    - git submodule update --init --remote --recursive # 更新submodule代码
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo -v --gc
    - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master  # branch contains blog content
  on:
    branch: code  # branch contains Hugo generator code

```
