### ISSUE TITLE
代码显示有点不习惯, 如何改成带行号的,黑色背景的.

### ISSUE THREAD

**Issue by yezihack** [xianmin/hugo-theme-jane#285]
默认样式, 感觉不习惯.
![image](https://user-images.githubusercontent.com/11530866/75136005-38b14b00-571e-11ea-82d9-b918b3453f0f.png)

如何改成这样:
![image](https://user-images.githubusercontent.com/11530866/75136082-78783280-571e-11ea-92b9-750ea0bc46b2.png)

前端太差了,谁能帮我把样式给写出来.感谢不尽.

**Comment by xmasuhai** [comment]
你可以看看
https://github.com/xianmin/hugo-theme-jane/issues/133
可以close掉了

You'll have to turn on syntax highlight 
https://github.com/xianmin/hugo-theme-jane/blob/master/exampleSite/full-config.toml#L15
从代码第十五行开始看
在配置文件里加上

```TOML
# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"
```

具体改样式 请参考
https://gohugo.io/content-management/syntax-highlighting/
