### ISSUE TITLE
Sticky navbar

### ISSUE THREAD

**Issue by LITUATUI** [xianmin/hugo-theme-jane#354]
Please add the option to make the navbar sticky, or make it default.

Thanks!

**Comment by paskal** [comment]
Adding in https://github.com/xianmin/hugo-theme-jane/pull/424

**Comment by paskal** [comment]
## Sticky Desktop Header Instructions

For those who want to implement sticky desktop headers without modifying the theme, here are CSS-only solutions for both v2 and v3 of hugo-theme-jane:

### For hugo-theme-jane v2

Create a file `/static/css/sticky-header.css` with:

```css
/* Sticky desktop header for v2 */
@media screen and (min-width: 1081px) {
  .header {
    position: sticky;
    top: 0;
    background-color: #fff;
    box-shadow: 0 2px 2px rgba(0, 0, 0, 0.1);
    z-index: 99;
    padding: 20px 0;
  }
}
```

### For hugo-theme-jane v3

Create a file `/static/css/sticky-header.css` with:

```css
/* Sticky desktop header for v3 */
@media screen and (min-width: 1025px) {
  .site-header {
    position: sticky;
    top: 0;
    z-index: 1000;
  }
}
```

### How to apply

1. Create the CSS file in `/static/css/sticky-header.css`
2. Add the CSS link to your site's header by creating/editing `/layouts/partials/custom_head.html`:
```html
<link rel="stylesheet" href="{{ "css/sticky-header.css" | relURL }}">
```

**Note:** v3 already has sticky header for mobile (`position: sticky` in `.site-header` at mobile breakpoint). The v2 mobile navbar uses `position: fixed` which is always sticky.
