### ISSUE TITLE
cannot remove rss logo

### ISSUE THREAD

**Issue by gkdgo** [xianmin/hugo-theme-jane#361]
<img width="232" alt="iShot_2023-05-23_11 57 51" src="https://github.com/xianmin/hugo-theme-jane/assets/55651847/9d0f1283-2768-4fb3-ad17-e38a92fbc8aa">

my config
```toml
  [params.social]                                         # 社交链接
    a-email = "http://localhost:1313"
    # b-stack-overflow = "http://localhost:1313"
    # c-twitter = "http://localhost:1313"
    # d-facebook = "http://localhost:1313"
    # e-linkedin = "http://localhost:1313"
    # f-google = "http://localhost:1313"
    g-github = "http://localhost:1313"
    # h-weibo = "http://localhost:1313"
    # i-zhihu = "http://localhost:1313"
    # j-douban = "http://localhost:1313"
    # k-pocket = "http://localhost:1313"
    # l-tumblr = "http://localhost:1313"
    # m-instagram = "http://localhost:1313"
    # n-gitlab = "http://localhost:1313"
    # o-goodreads = "http://localhost:1313"
    # p-coding = "http://localhost:1313"
    # q-bilibili = "http://localhost:1313"
    # r-codeforces = "http://localhost:1313"
    # s-mastodon = "http://localhost:1313"
    # t-youtube = "http://localhost:1313"
    # u-twitch = "http://localhost:1313"

```
