### ISSUE TITLE
Notice: ♻️ Migration from highlight.js to Chroma

### ISSUE THREAD

**Issue by xianmin** [xianmin/hugo-theme-jane#46]
A big thank you to @Zebradil [Pull Request #43](https://github.com/xianmin/hugo-theme-jane/pull/43). Now the theme code highlighting migrate from highlight.js to Chroma.

If you use the old `hugo-theme-jane` version, there is one thing to note. To enable new code highlighting, you need add some config in your site `config.toml` :

```toml
# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
pygmentsUseClasses = true # Use CSS classes to format highlighted code
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"
```

**related commit:** https://github.com/xianmin/hugo-theme-jane/commit/e683155138ca3144c5a84426df323b15c2a1a708

**related issues:** [Why chose client-side code highlighting over builtin server-side func? · Issue #28](https://github.com/xianmin/hugo-theme-jane/issues/28)

**related links:**

- [Syntax Highlighting | Hugo](https://gohugo.io/content-management/syntax-highlighting/)
- [Hugo 0.28: High-speed Syntax Highlighting! | Hugo](https://gohugo.io/news/0.28-relnotes/)
