### ISSUE TITLE
question - possible to get sticky post?

### ISSUE THREAD

**Issue by chad-bennett** [xianmin/hugo-theme-jane#65]
hello. new to hugo.

i'm looking to have a sticky post that sits at the top of the post list forever. is there a way to do this with hugo and/or jane theme? 

have been looking for hours and can't find an answer. thanks for any help anyone can provide. 

[https://chad-bennett.github.io/home/](https://chad-bennett.github.io/home/)

**Comment by xianmin** [comment]
The easy way: 
Add `Front Matter` config `weight: 1` in your sticky post.

``` yaml
---
title: "Sticky post"
date: 2018-06-01
weight: 1
---
```
