### ISSUE TITLE
How to change logo font

### ISSUE THREAD

**Issue by alcir** [xianmin/hugo-theme-jane#7]
Excuse me. I'm not an expert of CSS and so on.
How can I change the font in the a class="logo", that is Chancery by default. Let's say I want to use Comfortaa https://fonts.google.com/specimen/Comfortaa

Thanks

**Comment by xianmin** [comment]
The easy way:

1. Create a `custom.css` file under your site `./static/css/` folder.
2. Modify the `custom.css` file like this:

``` css
@import url(https://fonts.googleapis.com/css?family=Comfortaa);

.logo {
  font-family: Comfortaa !important;
}
```
3. Modify your site `config` file `customCSS` option : `customCSS = ['custom.css']`
